import { chromium } from 'playwright';
const BASE='http://localhost:3300', P='febf025b8e62';
const b=await chromium.launch(); const page=await b.newPage({viewport:{width:1440,height:1000}});
const writes=[];
page.on('request',r=>{ if(!['GET','HEAD','OPTIONS'].includes(r.method())) writes.push(`${r.method()} ${r.url().split('/api/')[1]||r.url()}`); });
await page.goto(`${BASE}/p/${P}/dtos/probe-dto`,{waitUntil:'networkidle'});
await page.waitForTimeout(2500);
const prose=await page.evaluate(()=>[...document.querySelectorAll('.prose-spec')].map(e=>e.innerText));
console.log('dto prose:',JSON.stringify(prose));
console.log('writes:',writes);
const after=await (await fetch(`${BASE}/api/projects/${P}/dtos/probe-dto`)).json();
console.log('dto description after open:',JSON.stringify(after.data.description));
await b.close();
