/**
 * Item 31 — `/api/{type}s`, generated by the host from `data.schema`.
 *
 * Driven against a type with NO `backend.routes` at all (the fixture module),
 * because that is the only place the generated router is reachable in tier E:
 * it is mounted after each type's own router, so the six built-ins still answer
 * from theirs until tier K deletes them. A test that used `ui-view` here would
 * pass while exercising the code this replaces.
 *
 * The fixture is also the honest subject: it is a plugin-contributed type that
 * declares its data and nothing else — the shape item 63's plug-and-play test
 * is about, and the one the six built-ins become.
 */

import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import request from 'supertest';
import { createTestApp, type TestApp } from '../../helpers/test-app.js';
import { fixtureModule } from '../../helpers/fixture-module.js';
import type { DataDeclaration } from '../../../src/shared/plugin-host/data-schema.js';

/**
 * One of each flag the input schemas act on: a required field, an enum with a
 * default, a clearable field (the tri-state's subject) and a value collection.
 */
const WIDGET_DATA: DataDeclaration = {
  schema: {
    name: { kind: 'string', required: true },
    status: { kind: 'enum', values: ['draft', 'live'], default: 'draft' },
    note: { kind: 'string', clearable: true },
    /**
     * A field whose COLUMN differs from its NAME. The first version of this
     * fixture had none, and that gap hid a data loss: `hydrate` keys the row by
     * column while the write path is keyed by field, so an unrelated PATCH
     * blanked every camelCase field of a declaratively-authored type.
     */
    ownerSlug: { kind: 'string', column: 'owner_slug', clearable: true },
    /** Same idea for `required`: this one made the entity UNPATCHABLE. */
    kindLabel: { kind: 'string', column: 'kind_label', required: true, default: 'plain' },
    /** An opaque value, to pin that it round-trips rather than gaining a layer of escaping per write. */
    blob: { kind: 'json' },
    parts: {
      kind: 'collection',
      collection: 'value',
      item: { kind: 'object', fields: { label: { kind: 'string', required: true } } },
    },
    /**
     * A value collection with `keyFields`, so it projects to a table of its own
     * rather than to embedded JSON — the `endpoint.linkedDtos` shape. It is not
     * on the parent row, so it is exactly what a naive merge cannot see.
     */
    links: {
      kind: 'collection',
      collection: 'value',
      keyFields: ['target'],
      item: {
        kind: 'object',
        fields: {
          target: { kind: 'string', required: true },
          rank: { kind: 'number' },
        },
      },
    },
    createdAt: { kind: 'string', column: 'created_at', systemManaged: true, computedDefault: 'now' },
    updatedAt: { kind: 'string', column: 'updated_at', systemManaged: true, computedDefault: 'now' },
  },
};

describe('generated CRUD routes for a serviceless declarative type', () => {
  let t: TestApp;

  beforeEach(async () => {
    t = await createTestApp({
      extraModules: [fixtureModule('widget', { data: WIDGET_DATA })],
    });
  });
  afterEach(() => t.cleanup());

  it('POST mints the slug from slugPattern and answers 201 with the entity', async () => {
    const res = await request(t.app).post('/api/widgets').send({ name: 'Order Form' });
    expect(res.status).toBe(201);
    // `slugify(name)` — the DECLARED rule, evaluated server-side for the first
    // time in 0.2.9. Tier A shipped the grammar and left every type's slug
    // still being minted by its own hand-written function.
    expect(res.body.data.slug).toBe('order-form');
    // The default the declaration carries, applied by the write path.
    expect(res.body.data.status).toBe('draft');
  });

  /**
   * An explicit slug wins, and a collision on one REFUSES.
   *
   * Tier E suffixed here as well, on the strength of `ac`'s comment — but even
   * `ac` threw `SLUG_CONFLICT` when the caller named the slug, and landing
   * somewhere other than where you were told to is worse than failing. A DERIVED
   * collision follows the type's declared `slugConflict`, which defaults to the
   * same refusal (`widget` declares nothing); `ac` and `diagram` opt into the
   * suffix because their slugs are slugified prose.
   */
  it('an explicit slug wins, and a collision on one is refused rather than renamed', async () => {
    expect((await request(t.app).post('/api/widgets').send({ name: 'A', slug: 'pinned' })).body.data.slug).toBe('pinned');
    const second = await request(t.app).post('/api/widgets').send({ name: 'B', slug: 'pinned' });
    expect(second.status).toBe(409);
    expect(second.body.error.code).toBe('SLUG_CONFLICT');
  });

  it('refuses a DERIVED collision too, for a type that declares no slugConflict', async () => {
    expect((await request(t.app).post('/api/widgets').send({ name: 'Order Form' })).status).toBe(201);
    const dup = await request(t.app).post('/api/widgets').send({ name: 'Order Form' });
    expect(dup.status).toBe(409);
    expect(dup.body.error.code).toBe('SLUG_CONFLICT');
  });

  it('GET / answers the L4 envelope, not the retired per-type key', async () => {
    await request(t.app).post('/api/widgets').send({ name: 'One' });
    await request(t.app).post('/api/widgets').send({ name: 'Two' });

    const res = await request(t.app).get('/api/widgets');
    expect(res.status).toBe(200);
    // `{ data, total }` — L4's REST response format. `{ items, total, hasMore }`
    // is the MCP transport's envelope and stays there; `{ widgets: [...] }` was
    // never a written contract, only what six hand-written routers happened to do.
    expect(res.body).toHaveProperty('data');
    expect(res.body).toHaveProperty('total', 2);
    expect(res.body).not.toHaveProperty('widgets');
    expect(res.body).not.toHaveProperty('items');
  });

  it('re-attaches the audit stamp no L9 view emits', async () => {
    await request(t.app).post('/api/widgets').send({ name: 'Stamped' });
    const res = await request(t.app).get('/api/widgets/stamped');
    // `createdAt`/`updatedAt` are `systemManaged`, so `hydrate` lifts them out
    // of `data` and no view carries them — but every list row and detail header
    // renders them. Without this the client shows "updated Invalid Date".
    expect(typeof res.body.data.createdAt).toBe('string');
    expect(typeof res.body.data.updatedAt).toBe('string');
  });

  it('PATCH is a tri-state: omitted keeps, null clears, a value replaces', async () => {
    await request(t.app).post('/api/widgets').send({ name: 'Tri', note: 'original', status: 'live' });

    // omitted → unchanged. The projection upsert names every column, so a naive
    // implementation blanks `status` and `note` on any partial write.
    const kept = await request(t.app).patch('/api/widgets/tri').send({ name: 'Tri Renamed' });
    expect(kept.status).toBe(200);
    expect(kept.body.data.note).toBe('original');
    expect(kept.body.data.status).toBe('live');

    // null → cleared, legal because `note` is `clearable`.
    const cleared = await request(t.app).patch('/api/widgets/tri').send({ note: null });
    expect(cleared.status).toBe(200);
    expect(cleared.body.data.note).toBeNull();
  });

  /**
   * The four defects a high-effort review found in the first version of the
   * generic write door. Each is data loss, and each was invisible to the
   * original fixture because it declared no column override, no table-backed
   * collection and no opaque value.
   */
  /**
   * These assert against the PROJECTION rather than the response body, because
   * the projection is what the bugs destroyed — and because a generic view
   * (a type with no computed views, which is the whole point of this fixture)
   * spreads the row and is therefore keyed by COLUMN name, so the response is
   * the wrong instrument for a defect that is about field-vs-column keying.
   */
  const row = () => t.db.prepare(`SELECT * FROM widget WHERE slug = ?`).get('owned') as Record<string, unknown>;

  it('an unrelated PATCH leaves a column-renamed field alone', async () => {
    await request(t.app).post('/api/widgets').send({ name: 'Owned', ownerSlug: 'me', kindLabel: 'special' });
    const patched = await request(t.app).patch('/api/widgets/owned').send({ name: 'Owned Renamed' });
    expect(patched.status).toBe(200);
    // Was `null`: the merge base was keyed by column (`owner_slug`) and the
    // upsert reads field names, so `ownerSlug` was absent and written as default.
    expect(row().owner_slug).toBe('me');
    // Was a 400 "kindLabel is required" — the same miss, on a required field,
    // made the entity impossible to patch at all.
    expect(row().kind_label).toBe('special');
  });

  it('an unrelated PATCH leaves a table-backed value collection alone', async () => {
    await request(t.app)
      .post('/api/widgets')
      .send({ name: 'Linked', links: [{ target: 'a', rank: 1 }, { target: 'b', rank: 2 }] });
    const links = () => t.rawReader.readCollection('widget', 'linked', 'links');
    expect(links()).toHaveLength(2);

    const patched = await request(t.app).patch('/api/widgets/linked').send({ note: 'unrelated' });
    expect(patched.status).toBe(200);
    // Was `[]`: the collection lives in its own table, so the merge base never
    // carried it and the upsert read "absent" as "empty" and DELETEd every row.
    expect(links()).toHaveLength(2);
  });

  it('a rejected payload does not leave the entity renamed', async () => {
    await request(t.app).post('/api/widgets').send({ name: 'Stable' });
    const res = await request(t.app)
      .patch('/api/widgets/stable')
      .send({ newSlug: 'moved', status: 'archived' });
    expect(res.status).toBe(400);
    // The rename used to commit in its own transaction BEFORE the payload
    // write, so a 400 left the row moved, the file at the old slug, and the
    // next rebuild resurrecting the old entity as a second one.
    expect((await request(t.app).get('/api/widgets/stable')).status).toBe(200);
    expect((await request(t.app).get('/api/widgets/moved')).status).toBe(404);
  });

  it('round-trips an opaque json value instead of re-escaping it', async () => {
    await request(t.app).post('/api/widgets').send({ name: 'Blobby', blob: { a: 1, b: ['x'] } });
    const res = await request(t.app).get('/api/widgets/blobby');
    // Came back as the STRING '{"a":1,"b":["x"]}' — `hydrate` decoded only
    // object/record/collection columns, and `persist` rewrites the file from the
    // row, so every write added another layer of escaping to the source of truth.
    expect(res.body.data.blob).toEqual({ a: 1, b: ['x'] });

    // A scalar arm too — this is what `design-system`'s token values are.
    await request(t.app).post('/api/widgets').send({ name: 'Scalar', blob: '#2563eb' });
    expect((await request(t.app).get('/api/widgets/scalar')).body.data.blob).toBe('#2563eb');
  });

  it('records the tags on the version it captures, not an empty list', async () => {
    const created = await request(t.app).post('/api/widgets').send({ name: 'Tagged', tags: ['keep'] });
    expect(created.status).toBe(201);
    const captured = t.db
      .prepare(`SELECT data FROM entity_version WHERE entity_type = 'widget' AND entity_slug = 'tagged' ORDER BY version`)
      .all() as Array<{ data: string }>;
    expect(captured.length).toBeGreaterThan(0);
    // Tags were assigned AFTER the capture, so every version recorded `tags: []`
    // and restoring one — or diffing it in a release — dropped them.
    expect(JSON.parse(captured[0]!.data).tags).toEqual(['keep']);
  });

  it('accepts a create that omits a required field carrying a default', async () => {
    // The generated schema calls `kindLabel` optional because it has a default;
    // the write path used to reject it as missing anyway, so the schema and the
    // only door it feeds disagreed about the same declaration.
    const res = await request(t.app).post('/api/widgets').send({ name: 'Defaulted' });
    expect(res.status).toBe(201);
    const stored = t.db.prepare(`SELECT kind_label FROM widget WHERE slug = ?`).get('defaulted') as {
      kind_label: string;
    };
    expect(stored.kind_label).toBe('plain');
  });

  it('rejects null for a field that is not clearable, with 400 and not 500', async () => {
    await request(t.app).post('/api/widgets').send({ name: 'Strict' });
    const res = await request(t.app).patch('/api/widgets/strict').send({ name: null });
    expect(res.status).toBe(400);
    expect(res.body.error.code).toBe('VALIDATION');
  });

  it('rejects a value outside a declared enum instead of coercing it', async () => {
    const res = await request(t.app).post('/api/widgets').send({ name: 'Bad', status: 'archived' });
    expect(res.status).toBe(400);
    expect(res.body.error.code).toBe('VALIDATION');
  });

  it('rejects a create missing a required field', async () => {
    const res = await request(t.app).post('/api/widgets').send({ status: 'live' });
    expect(res.status).toBe(400);
  });

  it('renames through newSlug and leaves nothing at the old one', async () => {
    await request(t.app).post('/api/widgets').send({ name: 'Before' });
    const renamed = await request(t.app).patch('/api/widgets/before').send({ newSlug: 'after' });
    expect(renamed.status).toBe(200);
    expect(renamed.body.data.slug).toBe('after');
    expect((await request(t.app).get('/api/widgets/before')).status).toBe(404);
    expect((await request(t.app).get('/api/widgets/after')).status).toBe(200);
  });

  it('round-trips a value collection', async () => {
    await request(t.app)
      .post('/api/widgets')
      .send({ name: 'Composite', parts: [{ label: 'head' }, { label: 'tail' }] });
    const res = await request(t.app).get('/api/widgets/composite');
    expect(res.body.data.parts).toEqual([{ label: 'head' }, { label: 'tail' }]);
  });

  it('DELETE removes the entity and reports what pointed at it', async () => {
    await request(t.app).post('/api/widgets').send({ name: 'Doomed' });
    const res = await request(t.app).delete('/api/widgets/doomed');
    expect(res.status).toBe(200);
    expect(res.body).toMatchObject({ deleted: true, brokenReferences: [] });
    expect((await request(t.app).get('/api/widgets/doomed')).status).toBe(404);
  });

  it('404s an unknown slug rather than answering with an empty body', async () => {
    const res = await request(t.app).get('/api/widgets/nope');
    expect(res.status).toBe(404);
    expect(res.body.error.code).toBe('NOT_FOUND');
  });

  it('filters by tag, and search ranks rather than filtering', async () => {
    await request(t.app).post('/api/widgets').send({ name: 'Alpha', tags: ['keep'] });
    await request(t.app).post('/api/widgets').send({ name: 'Beta' });

    const tagged = await request(t.app).get('/api/widgets?tags=keep');
    expect(tagged.body.total).toBe(1);
    expect(tagged.body.data[0].slug).toBe('alpha');

    const searched = await request(t.app).get('/api/widgets?search=Beta');
    expect(searched.body.data.map((d: { slug: string }) => d.slug)).toContain('beta');
  });

  /**
   * Every narrowing the caller asked for survives the search branch.
   *
   * Search and list are different core operations, and keeping them apart is
   * what stopped the retired per-type SQL from dropping the ranking. What that
   * must NOT cost is the narrowing itself: the list pages send `tags`, `search`
   * and the field dropdowns in ONE request, so a search path that quietly
   * ignored `tags` made a visibly-selected tag chip stop applying the moment you
   * typed — the filter is still on screen, the rows no longer obey it.
   */
  it('ANDs the tag filter with the ranking, instead of dropping it once search is present', async () => {
    await request(t.app).post('/api/widgets').send({ name: 'Beta Keeper', tags: ['keep'] });
    await request(t.app).post('/api/widgets').send({ name: 'Beta Stranger' });

    const both = await request(t.app).get('/api/widgets?search=Beta&tags=keep');
    expect(both.status).toBe(200);
    const slugs = both.body.data.map((d: { slug: string }) => d.slug);
    expect(slugs).toEqual(['beta-keeper']);
    expect(both.body.total).toBe(1);
  });

  /**
   * The page size a list page gets when it asks for none.
   *
   * The M39 core defaults to 50 — right for an agent over stdio, wrong for a
   * page with no pagination control, where it silently hid the 51st entity of
   * every type. Every retired service defaulted to 200.
   */
  it('defaults to a page big enough for a list page with no pagination UI', async () => {
    for (let i = 0; i < 60; i += 1) {
      await request(t.app).post('/api/widgets').send({ name: `W ${i}` });
    }
    const res = await request(t.app).get('/api/widgets');
    expect(res.body.data).toHaveLength(60);
    expect(res.body.total).toBe(60);
  });

  /**
   * The un-staging, asserted rather than assumed — the other half of the test
   * tier E wrote here.
   *
   * Tier E pinned `/api/ui-views` answering `{ uiViews: [...] }`, because
   * `ui-view` still shipped a `backend.routes` router mounted ahead of the
   * generated one. Tier K deleted that router, so a BUILT-IN type now lands on
   * the same generated envelope a serviceless plugin type does. The assertion
   * was deliberately two-sided so this could not be satisfied silently in both
   * states: it had to be edited, and here it is.
   */
  it('serves a BUILT-IN type from the generated router, its own having been deleted', async () => {
    const res = await request(t.app).get('/api/ui-views');
    expect(res.status).toBe(200);
    expect(res.body).toHaveProperty('data');
    expect(res.body).toHaveProperty('total');
    expect(res.body).not.toHaveProperty('uiViews');
  });

  /**
   * `ac`'s declared `defaultPredicate`, over REST — what `AcService.list`'s
   * hand-written `status` default used to do, and the escape hatch that goes
   * with it.
   *
   * `?status=all` is not a value: it LIFTS the default. The sentinel is
   * implemented in `slugsMatching`, not here, so `filters: { status: 'all' }`
   * over MCP means the same thing — implementing it in the router made it mean
   * "everything" over HTTP and "nothing" over MCP.
   */
  it('applies ac\'s declared default, and lets ?status=all lift it', async () => {
    const active = await request(t.app).post('/api/acs').send({ text: 'still true' });
    expect(active.status).toBe(201);
    const gone = await request(t.app).post('/api/acs').send({ text: 'no longer true' });
    await request(t.app).patch(`/api/acs/${gone.body.data.slug}`).send({ status: 'deprecated' });

    const def = await request(t.app).get('/api/acs');
    expect(def.body.data.map((a: { slug: string }) => a.slug)).toEqual([active.body.data.slug]);

    const all = await request(t.app).get('/api/acs?status=all');
    expect(all.body.data).toHaveLength(2);

    const deprecated = await request(t.app).get('/api/acs?status=deprecated');
    expect(deprecated.body.data.map((a: { slug: string }) => a.slug)).toEqual([gone.body.data.slug]);
  });

  /**
   * Item 58's allowlist, restated as an enum rather than lost with the service.
   *
   * `EndpointService.requireMethod` rejected anything outside the five verbs;
   * declared as a plain `string`, `{ method: 'get' }` and `{ method: 'FETCH' }`
   * were both stored verbatim, and code generated from the spec would carry a
   * verb that does not exist.
   */
  it('rejects an HTTP method the declaration does not name', async () => {
    expect((await request(t.app).post('/api/endpoints').send({ method: 'FETCH', path: '/x' })).status).toBe(400);
    // Lower case is a rejection too, not a silent upper-casing: a declaration
    // says what is valid, it does not rewrite the caller's payload.
    expect((await request(t.app).post('/api/endpoints').send({ method: 'get', path: '/x' })).status).toBe(400);
    expect((await request(t.app).post('/api/endpoints').send({ method: 'GET', path: '/x' })).status).toBe(201);
  });

  /**
   * Item 56, and the brief's headline example.
   *
   * `DiagramService.readFormat` mapped everything that was not `'d2'` onto
   * `'mermaid'`, so `POST /api/diagrams` with `format: 'graphviz'` answered 201
   * and stored a diagram in a language the author did not ask for — a silent
   * rewrite of the payload, discoverable only by re-reading the entity. The
   * declaration already said `enum ['mermaid','d2']`; deleting the coercion is
   * what lets it be enforced.
   */
  it('rejects a diagram format the declaration does not name, instead of coercing it', async () => {
    const coerced = await request(t.app)
      .post('/api/diagrams')
      .send({ caption: 'Flow', format: 'graphviz', source: 'digraph { a -> b }' });
    expect(coerced.status).toBe(400);

    for (const format of ['mermaid', 'd2']) {
      const ok = await request(t.app)
        .post('/api/diagrams')
        .send({ caption: `Flow ${format}`, format, source: 'x' });
      expect(ok.status).toBe(201);
      expect(ok.body.data.format).toBe(format);
    }
  });

  /**
   * The other half of what left with `DiagramService`: it ran `validateDiagram
   * Source` on every create/update and answered `{ slug, warnings }`.
   *
   * Item 56 puts that validator in `validate_diagram` alone — a PRE-flight tool
   * the author calls with a source string, before an entity exists. So the write
   * path accepts an unparseable source verbatim and says nothing about it, which
   * is the same move `ui-view` and `design-system` made in K2: linting belongs
   * where the result is read, not on the one code path that happens to write.
   */
  it('stores an unparseable diagram source verbatim, and says nothing about it', async () => {
    const res = await request(t.app)
      .post('/api/diagrams')
      .send({ caption: 'Broken', source: 'not a diagram at all' });
    expect(res.status).toBe(201);
    expect(res.body.data).not.toHaveProperty('warnings');
    expect(res.body.data.source).toBe('not a diagram at all');
    // Default format still applies — it is `default: 'mermaid'` on the field.
    expect(res.body.data.format).toBe('mermaid');
  });
});
