/**
 * Item 31 — `/api/{type}s`, generated by the host from `data.schema`.
 *
 * Driven against a type with NO `backend.routes` at all (the fixture module),
 * because that is the only place the generated router is reachable in tier E:
 * it is mounted after each type's own router, so the six built-ins still answer
 * from theirs until tier K deletes them. A test that used `ui-view` here would
 * pass while exercising the code this replaces.
 *
 * The fixture is also the honest subject: it is a plugin-contributed type that
 * declares its data and nothing else — the shape item 63's plug-and-play test
 * is about, and the one the six built-ins become.
 */

import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import request from 'supertest';
import { createTestApp, type TestApp } from '../../helpers/test-app.js';
import { fixtureModule } from '../../helpers/fixture-module.js';
import type { DataDeclaration } from '../../../src/shared/plugin-host/data-schema.js';

/**
 * One of each flag the input schemas act on: a required field, an enum with a
 * default, a clearable field (the tri-state's subject) and a value collection.
 */
const WIDGET_DATA: DataDeclaration = {
  schema: {
    name: { kind: 'string', required: true },
    status: { kind: 'enum', values: ['draft', 'live'], default: 'draft' },
    note: { kind: 'string', clearable: true },
    /**
     * A field whose COLUMN differs from its NAME. The first version of this
     * fixture had none, and that gap hid a data loss: `hydrate` keys the row by
     * column while the write path is keyed by field, so an unrelated PATCH
     * blanked every camelCase field of a declaratively-authored type.
     */
    ownerSlug: { kind: 'string', column: 'owner_slug', clearable: true },
    /** Same idea for `required`: this one made the entity UNPATCHABLE. */
    kindLabel: { kind: 'string', column: 'kind_label', required: true, default: 'plain' },
    /** An opaque value, to pin that it round-trips rather than gaining a layer of escaping per write. */
    blob: { kind: 'json' },
    parts: {
      kind: 'collection',
      collection: 'value',
      item: { kind: 'object', fields: { label: { kind: 'string', required: true } } },
    },
    /**
     * A value collection with `keyFields`, so it projects to a table of its own
     * rather than to embedded JSON — the `endpoint.linkedDtos` shape. It is not
     * on the parent row, so it is exactly what a naive merge cannot see.
     */
    links: {
      kind: 'collection',
      collection: 'value',
      keyFields: ['target'],
      item: {
        kind: 'object',
        fields: {
          target: { kind: 'string', required: true },
          rank: { kind: 'number' },
        },
      },
    },
    createdAt: { kind: 'string', column: 'created_at', systemManaged: true, computedDefault: 'now' },
    updatedAt: { kind: 'string', column: 'updated_at', systemManaged: true, computedDefault: 'now' },
  },
};

describe('generated CRUD routes for a serviceless declarative type', () => {
  let t: TestApp;

  beforeEach(async () => {
    t = await createTestApp({
      extraModules: [fixtureModule('widget', { data: WIDGET_DATA })],
    });
  });
  afterEach(() => t.cleanup());

  it('POST mints the slug from slugPattern and answers 201 with the entity', async () => {
    const res = await request(t.app).post('/api/widgets').send({ name: 'Order Form' });
    expect(res.status).toBe(201);
    // `slugify(name)` — the DECLARED rule, evaluated server-side for the first
    // time in 0.2.9. Tier A shipped the grammar and left every type's slug
    // still being minted by its own hand-written function.
    expect(res.body.data.slug).toBe('order-form');
    // The default the declaration carries, applied by the write path.
    expect(res.body.data.status).toBe('draft');
  });

  it('an explicit slug wins, and a collision takes the -2 suffix rather than failing', async () => {
    expect((await request(t.app).post('/api/widgets').send({ name: 'A', slug: 'pinned' })).body.data.slug).toBe('pinned');
    const second = await request(t.app).post('/api/widgets').send({ name: 'B', slug: 'pinned' });
    expect(second.status).toBe(201);
    expect(second.body.data.slug).toBe('pinned-2');
  });

  it('GET / answers the L4 envelope, not the retired per-type key', async () => {
    await request(t.app).post('/api/widgets').send({ name: 'One' });
    await request(t.app).post('/api/widgets').send({ name: 'Two' });

    const res = await request(t.app).get('/api/widgets');
    expect(res.status).toBe(200);
    // `{ data, total }` — L4's REST response format. `{ items, total, hasMore }`
    // is the MCP transport's envelope and stays there; `{ widgets: [...] }` was
    // never a written contract, only what six hand-written routers happened to do.
    expect(res.body).toHaveProperty('data');
    expect(res.body).toHaveProperty('total', 2);
    expect(res.body).not.toHaveProperty('widgets');
    expect(res.body).not.toHaveProperty('items');
  });

  it('re-attaches the audit stamp no L9 view emits', async () => {
    await request(t.app).post('/api/widgets').send({ name: 'Stamped' });
    const res = await request(t.app).get('/api/widgets/stamped');
    // `createdAt`/`updatedAt` are `systemManaged`, so `hydrate` lifts them out
    // of `data` and no view carries them — but every list row and detail header
    // renders them. Without this the client shows "updated Invalid Date".
    expect(typeof res.body.data.createdAt).toBe('string');
    expect(typeof res.body.data.updatedAt).toBe('string');
  });

  it('PATCH is a tri-state: omitted keeps, null clears, a value replaces', async () => {
    await request(t.app).post('/api/widgets').send({ name: 'Tri', note: 'original', status: 'live' });

    // omitted → unchanged. The projection upsert names every column, so a naive
    // implementation blanks `status` and `note` on any partial write.
    const kept = await request(t.app).patch('/api/widgets/tri').send({ name: 'Tri Renamed' });
    expect(kept.status).toBe(200);
    expect(kept.body.data.note).toBe('original');
    expect(kept.body.data.status).toBe('live');

    // null → cleared, legal because `note` is `clearable`.
    const cleared = await request(t.app).patch('/api/widgets/tri').send({ note: null });
    expect(cleared.status).toBe(200);
    expect(cleared.body.data.note).toBeNull();
  });

  /**
   * The four defects a high-effort review found in the first version of the
   * generic write door. Each is data loss, and each was invisible to the
   * original fixture because it declared no column override, no table-backed
   * collection and no opaque value.
   */
  /**
   * These assert against the PROJECTION rather than the response body, because
   * the projection is what the bugs destroyed — and because a generic view
   * (a type with no computed views, which is the whole point of this fixture)
   * spreads the row and is therefore keyed by COLUMN name, so the response is
   * the wrong instrument for a defect that is about field-vs-column keying.
   */
  const row = () => t.db.prepare(`SELECT * FROM widget WHERE slug = ?`).get('owned') as Record<string, unknown>;

  it('an unrelated PATCH leaves a column-renamed field alone', async () => {
    await request(t.app).post('/api/widgets').send({ name: 'Owned', ownerSlug: 'me', kindLabel: 'special' });
    const patched = await request(t.app).patch('/api/widgets/owned').send({ name: 'Owned Renamed' });
    expect(patched.status).toBe(200);
    // Was `null`: the merge base was keyed by column (`owner_slug`) and the
    // upsert reads field names, so `ownerSlug` was absent and written as default.
    expect(row().owner_slug).toBe('me');
    // Was a 400 "kindLabel is required" — the same miss, on a required field,
    // made the entity impossible to patch at all.
    expect(row().kind_label).toBe('special');
  });

  it('an unrelated PATCH leaves a table-backed value collection alone', async () => {
    await request(t.app)
      .post('/api/widgets')
      .send({ name: 'Linked', links: [{ target: 'a', rank: 1 }, { target: 'b', rank: 2 }] });
    const links = () => t.rawReader.readCollection('widget', 'linked', 'links');
    expect(links()).toHaveLength(2);

    const patched = await request(t.app).patch('/api/widgets/linked').send({ note: 'unrelated' });
    expect(patched.status).toBe(200);
    // Was `[]`: the collection lives in its own table, so the merge base never
    // carried it and the upsert read "absent" as "empty" and DELETEd every row.
    expect(links()).toHaveLength(2);
  });

  it('a rejected payload does not leave the entity renamed', async () => {
    await request(t.app).post('/api/widgets').send({ name: 'Stable' });
    const res = await request(t.app)
      .patch('/api/widgets/stable')
      .send({ newSlug: 'moved', status: 'archived' });
    expect(res.status).toBe(400);
    // The rename used to commit in its own transaction BEFORE the payload
    // write, so a 400 left the row moved, the file at the old slug, and the
    // next rebuild resurrecting the old entity as a second one.
    expect((await request(t.app).get('/api/widgets/stable')).status).toBe(200);
    expect((await request(t.app).get('/api/widgets/moved')).status).toBe(404);
  });

  it('round-trips an opaque json value instead of re-escaping it', async () => {
    await request(t.app).post('/api/widgets').send({ name: 'Blobby', blob: { a: 1, b: ['x'] } });
    const res = await request(t.app).get('/api/widgets/blobby');
    // Came back as the STRING '{"a":1,"b":["x"]}' — `hydrate` decoded only
    // object/record/collection columns, and `persist` rewrites the file from the
    // row, so every write added another layer of escaping to the source of truth.
    expect(res.body.data.blob).toEqual({ a: 1, b: ['x'] });

    // A scalar arm too — this is what `design-system`'s token values are.
    await request(t.app).post('/api/widgets').send({ name: 'Scalar', blob: '#2563eb' });
    expect((await request(t.app).get('/api/widgets/scalar')).body.data.blob).toBe('#2563eb');
  });

  it('records the tags on the version it captures, not an empty list', async () => {
    const created = await request(t.app).post('/api/widgets').send({ name: 'Tagged', tags: ['keep'] });
    expect(created.status).toBe(201);
    const captured = t.db
      .prepare(`SELECT data FROM entity_version WHERE entity_type = 'widget' AND entity_slug = 'tagged' ORDER BY version`)
      .all() as Array<{ data: string }>;
    expect(captured.length).toBeGreaterThan(0);
    // Tags were assigned AFTER the capture, so every version recorded `tags: []`
    // and restoring one — or diffing it in a release — dropped them.
    expect(JSON.parse(captured[0]!.data).tags).toEqual(['keep']);
  });

  it('accepts a create that omits a required field carrying a default', async () => {
    // The generated schema calls `kindLabel` optional because it has a default;
    // the write path used to reject it as missing anyway, so the schema and the
    // only door it feeds disagreed about the same declaration.
    const res = await request(t.app).post('/api/widgets').send({ name: 'Defaulted' });
    expect(res.status).toBe(201);
    const stored = t.db.prepare(`SELECT kind_label FROM widget WHERE slug = ?`).get('defaulted') as {
      kind_label: string;
    };
    expect(stored.kind_label).toBe('plain');
  });

  it('rejects null for a field that is not clearable, with 400 and not 500', async () => {
    await request(t.app).post('/api/widgets').send({ name: 'Strict' });
    const res = await request(t.app).patch('/api/widgets/strict').send({ name: null });
    expect(res.status).toBe(400);
    expect(res.body.error.code).toBe('VALIDATION');
  });

  it('rejects a value outside a declared enum instead of coercing it', async () => {
    const res = await request(t.app).post('/api/widgets').send({ name: 'Bad', status: 'archived' });
    expect(res.status).toBe(400);
    expect(res.body.error.code).toBe('VALIDATION');
  });

  it('rejects a create missing a required field', async () => {
    const res = await request(t.app).post('/api/widgets').send({ status: 'live' });
    expect(res.status).toBe(400);
  });

  it('renames through newSlug and leaves nothing at the old one', async () => {
    await request(t.app).post('/api/widgets').send({ name: 'Before' });
    const renamed = await request(t.app).patch('/api/widgets/before').send({ newSlug: 'after' });
    expect(renamed.status).toBe(200);
    expect(renamed.body.data.slug).toBe('after');
    expect((await request(t.app).get('/api/widgets/before')).status).toBe(404);
    expect((await request(t.app).get('/api/widgets/after')).status).toBe(200);
  });

  it('round-trips a value collection', async () => {
    await request(t.app)
      .post('/api/widgets')
      .send({ name: 'Composite', parts: [{ label: 'head' }, { label: 'tail' }] });
    const res = await request(t.app).get('/api/widgets/composite');
    expect(res.body.data.parts).toEqual([{ label: 'head' }, { label: 'tail' }]);
  });

  it('DELETE removes the entity and reports what pointed at it', async () => {
    await request(t.app).post('/api/widgets').send({ name: 'Doomed' });
    const res = await request(t.app).delete('/api/widgets/doomed');
    expect(res.status).toBe(200);
    expect(res.body).toMatchObject({ deleted: true, brokenReferences: [] });
    expect((await request(t.app).get('/api/widgets/doomed')).status).toBe(404);
  });

  it('404s an unknown slug rather than answering with an empty body', async () => {
    const res = await request(t.app).get('/api/widgets/nope');
    expect(res.status).toBe(404);
    expect(res.body.error.code).toBe('NOT_FOUND');
  });

  it('filters by tag, and search ranks rather than filtering', async () => {
    await request(t.app).post('/api/widgets').send({ name: 'Alpha', tags: ['keep'] });
    await request(t.app).post('/api/widgets').send({ name: 'Beta' });

    const tagged = await request(t.app).get('/api/widgets?tags=keep');
    expect(tagged.body.total).toBe(1);
    expect(tagged.body.data[0].slug).toBe('alpha');

    const searched = await request(t.app).get('/api/widgets?search=Beta');
    expect(searched.body.data.map((d: { slug: string }) => d.slug)).toContain('beta');
  });

  /**
   * The staging this tier depends on, asserted rather than assumed.
   *
   * `ui-view` still ships a `backend.routes` router, mounted first, so it keeps
   * answering with its own `{ uiViews: [...] }` shape. When tier K deletes that
   * router this test flips to the generated envelope — and it should be edited
   * then, not silently satisfied by both.
   */
  it('does not shadow a type whose own router is still mounted', async () => {
    const res = await request(t.app).get('/api/ui-views');
    expect(res.status).toBe(200);
    expect(res.body).toHaveProperty('uiViews');
    expect(res.body).not.toHaveProperty('data');
  });
});
