/**
 * What a rendered `<inline_mention/>` is, now that no per-type view builds one.
 *
 * A chip is a LABEL AND A LINK. Before 0.2.22 each type contributed both from
 * its own `inline_mention` view (`label` from whichever field it considered its
 * name, `href` from a path prefix it hardcoded). The view axis is gone, so both
 * come from the projection: `title` is reserved and travels at every width, and
 * `href` is generated by the host from the type's `pathPrefix`.
 *
 * These cases exist because the failure mode is silent. A chip whose `label` and
 * `href` both went missing does not throw and does not 404 — it renders as bold
 * text where a link used to be, on a page that is otherwise fine. Nothing in the
 * status code, the console or the response shape says so.
 */

import { describe, expect, it } from 'vitest';
import { renderElementList, renderInlineMention } from './inline-renderer.js';

describe('renderInlineMention — the identity skeleton is enough to render a chip', () => {
  it('renders title + href as a markdown link', () => {
    expect(
      renderInlineMention({ type: 'ac', slug: 'ac-alpha', title: 'Alpha criterion', href: '/acs/ac-alpha' }),
    ).toBe('[Alpha criterion](/acs/ac-alpha)');
  });

  it('reads TITLE, not a label the projection no longer carries', () => {
    // The regression in one line: with `label` first in the chain, a record
    // carrying only `title` fell through to `slug` and printed the key.
    expect(renderInlineMention({ slug: 'ac-alpha', title: 'Alpha criterion', href: '/acs/ac-alpha' })).toContain(
      'Alpha criterion',
    );
  });

  it('still honours `label` for the SECTION chip, which is not an entity', () => {
    // A section has no `title` and no reserved field — it carries `headingText`
    // through its serializer as `label`, and it is the reason the chain has a
    // second link rather than one.
    expect(renderInlineMention({ type: 'section', label: 'Reading model', href: '/pages/x.md#abc' })).toBe(
      '[Reading model](/pages/x.md#abc)',
    );
  });

  it('degrades to a bold label rather than an empty link when href is absent', () => {
    expect(renderInlineMention({ slug: 'ac-alpha', title: 'Alpha criterion' })).toBe('**Alpha criterion**');
  });

  it('falls back to the slug for a row read before its title exists', () => {
    expect(renderInlineMention({ slug: 'ac-alpha' })).toBe('**ac-alpha**');
  });
});

describe('renderElementList — one table for every type', () => {
  it('prints slug and title, with no shape sniffing', () => {
    const out = renderElementList([
      { slug: 'a', title: 'Alpha' },
      { slug: 'b', title: 'Beta' },
    ]);
    expect(out).toContain('| `a` | Alpha |');
    expect(out).toContain('| `b` | Beta |');
  });

  it('says a list is empty rather than emitting a headerless table', () => {
    expect(renderElementList([])).toBe('_empty list_');
  });
});
