/**
 * Shared HTTP error class + response handler used by every API client
 * (cross-cutting + per-entity slices). Lives in lib/ because it is a
 * primitive, not an entity-bound concern.
 *
 * M31: also owns the project-scoped API base. The server injects
 * `window.__C4S_PROJECT__` per `/p/<id>/` route; every project-scoped call
 * goes through `apiFetch`, which rewrites a leading `/api/` to
 * `/api/projects/<id>/`. Workspace-scope calls (`/api/workspace*`) and
 * absolute peer URLs use plain `fetch` and pass through untouched.
 */

/** Project id injected by the server into the served HTML (12 hex chars). */
export const PROJECT_ID: string =
  (typeof window !== 'undefined' && window.__C4S_PROJECT__?.id) || '';

/** Prefix for every project-scoped API call. */
export const API_BASE = PROJECT_ID ? `/api/projects/${PROJECT_ID}` : '/api';

/**
 * fetch() with the project prefix applied to relative `/api/…` inputs.
 * Absolute URLs (e.g. a peer `serverUrl` in chat hooks) pass through.
 */
export function apiFetch(input: string | URL | Request, init?: RequestInit): Promise<Response> {
  if (typeof input === 'string' && input.startsWith('/api/')) {
    return fetch(`${API_BASE}${input.slice('/api'.length)}`, init);
  }
  return fetch(input, init);
}

/**
 * Normalize a router pathname to the in-app route space, whether or not the
 * basepath (`/p/<id>`) is included — covers both TanStack `useLocation()`
 * semantics and raw `window.location.pathname`.
 */
export function stripBase(pathname: string): string {
  if (PROJECT_ID && pathname.startsWith(`/p/${PROJECT_ID}`)) {
    const rest = pathname.slice(`/p/${PROJECT_ID}`.length);
    return rest === '' ? '/' : rest;
  }
  return pathname;
}

export class ApiError extends Error {
  constructor(
    public code: string,
    message: string,
    public status: number,
    /** Full `error` envelope from the server — carries extras like `field` for 422. */
    public details?: Record<string, unknown>,
  ) {
    super(message);
  }
}

export async function handle<T>(res: Response): Promise<T> {
  if (!res.ok) {
    const body = (await res.json().catch(() => null)) as
      | { error?: { code?: string; message?: string } & Record<string, unknown> }
      | null;
    const message = body?.error?.message ?? res.statusText;
    const code = body?.error?.code ?? 'HTTP_ERROR';
    throw new ApiError(code, message, res.status, body?.error);
  }
  return res.json() as Promise<T>;
}

/**
 * The L4 REST envelope, unwrapped — one entity.
 *
 * 2.0.0 tier K: every `/api/{type}s` route is generated by the host and answers
 * `{ data }` for one entity and `{ data, total }` for a list, replacing the
 * per-type key each hand-written router invented (`{ acs: [...] }`,
 * `{ dtos: [...] }`, …) — a shape that was never a written contract. The hooks
 * above this layer still want the payload itself, so the unwrapping lives here
 * once instead of in six copies of `entitiesApi`.
 */
export async function unwrap<T>(res: Response): Promise<T> {
  return (await handle<{ data: T }>(res)).data;
}

/** The same envelope, list form. `total` is dropped — no caller reads it yet. */
export async function unwrapList<T>(res: Response): Promise<T[]> {
  return (await handle<{ data: T[]; total: number }>(res)).data;
}
