/**
 * `ui-view`'s DOMAIN router — `GET /:slug/mockup`, the mockup document.
 *
 * The first route this type has ever contributed. Until 0.2.28 the envelope was
 * asymmetric (`design-system` had a service, `ui-view` had nothing); now each
 * type holds a different slot.
 *
 * WHY A ROUTE AND NOT A HOST-DERIVED PATH. The host can derive a path from an
 * L3 operation (`validate_diagram` is the precedent), but that mechanism does
 * not let anyone fix the SHAPE of the URL — and here a stable, hand-openable
 * address is a product requirement rather than a convenience. `/:slug/mockup`
 * is two segments and so cannot collide with the generated `GET /:slug`: a slug
 * never contains `/`.
 *
 * WHAT IT IS NOT: this is not a back door onto the raw `mockupHtml` value. That
 * field is `contentBearing` and still leaves only through the supervised
 * operation (`get_field_content` / `GET /api/entities/ui-view/:slug/content/
 * mockupHtml`); records keep carrying `hasMockupHtml`/`mockupHtmlBytes` instead.
 * The document is a DIFFERENT resource with a different subject — a composition
 * of two entities — and it takes nothing away from that exclusivity.
 *
 * TWO OPTIONAL QUERY PARAMS since 0.2.49 — `?state=` and `?mode=` — each an
 * axis of the preview variant, each landing as a `data-preview-*` attribute on
 * `<html>`. They are ORTHOGONAL and independently optional, and neither can
 * make the route answer anything but `200`: an unrecognised character drops the
 * param, an unrecognised NAME emits the attribute with a warning comment.
 *
 * A type deactivated in `config.entities` needs no check here: `mountBackend`
 * only walks ACTIVE types, so this router never mounts and the request 404s by
 * absence — exactly like every other path of the type.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { Router } from 'express';
import type { MockupMountContext } from '../../../host-kit/host-types.js';
import { parseGroups, parseModes } from '../../../design-system-domain.js';
import { DESIGN_SYSTEM_TYPE, UI_VIEW_TYPE } from '../../../identity.js';
import { renderMockupDocument } from './document.js';

/**
 * THE isolation contract for this document — one header, in its enforcing form.
 *
 * The material is `mockupHtml`: arbitrary HTML, in practice GENERATED BY AN
 * AGENT from specification prose. The threat is therefore not a remote attacker
 * but PROMPT INJECTION through spec content — a script that lands in the field
 * passes the literal-write rule untouched and would then be served from the
 * app's own origin. The L3 posture that "the trust boundary is the machine
 * boundary" does not cover code we put in our own field and serve ourselves.
 *
 * Every part of this string is load-bearing:
 *   - NO `allow-same-origin` — that is the entire point. The document gets an
 *     OPAQUE ORIGIN: `document.cookie` and `localStorage` throw, and a script
 *     inside it cannot read the response of any `/api/*` call it makes.
 *   - `allow-forms` / `allow-modals` do NOT weaken origin isolation, and
 *     without them a mockup with a form or a `confirm()` breaks silently.
 *     Removing them is not hardening; it is breaking the material.
 *   - no `allow-popups-to-escape-sandbox`, no `allow-top-navigation`.
 *
 * It must be a RESPONSE HEADER: never `-Report-Only`, and never
 * `<meta http-equiv>` — the `sandbox` directive cannot be delivered by a meta
 * tag at all, and the iframe's `sandbox` ATTRIBUTE only covers the document
 * while it sits in that frame, which is precisely the gap that matters when
 * someone pastes the URL into the address bar.
 *
 * Hardening goes through `sandbox`, NEVER through `script-src`: this document
 * requires inline-script and inline-style semantics by construction, so
 * `script-src` would kill the very thing being served.
 *
 * What it does NOT buy, stated plainly: the document still runs arbitrary JS in
 * its opaque origin (sandbox is not sanitisation), and OUTGOING requests to
 * `/api/*` still REACH the server — an opaque origin blocks reading the
 * response, not sending the request. No cookies are used anywhere, so there is
 * no session to steal, but a blind write is not closed by this header.
 *
 * 0.2.49 adds a SECOND INPUT CHANNEL to the threat model: the query params, and
 * they are the only input whose value ends up inside an attribute we write
 * ourselves. `mockupHtml` is pasted as element content and isolated by the
 * header above; `?state=` / `?mode=` are not content, so they get their own
 * whitelist — `SAFE_VARIANT` below.
 */
const SANDBOX_CSP = 'sandbox allow-scripts allow-forms allow-modals';

/**
 * The whitelist for BOTH variant query params — a SECURITY boundary, not format
 * validation.
 *
 * Query params are the route's second input channel and the ONLY one whose
 * value lands inside an HTML attribute. The `sandbox` header isolates the
 * document's origin; it does not sanitise what we ourselves write into it. So
 * the value is checked against a closed character class before it goes
 * anywhere near the composer — the same CHARACTER class the design system's
 * stylesheet generator applies to a mode name (`SAFE_CSS_NAME`), because these
 * are the two halves of one selector.
 *
 * The length cap is part of the boundary rather than a nicety: a megabyte of
 * legal characters is still a megabyte pasted into every response. It is also
 * the one place the two classes DIVERGE — `SAFE_CSS_NAME` has no cap and
 * `modes[].name` has no `maxLength`, so a mode name over 64 characters gets its
 * `[data-preview-mode="…"]` block emitted into the sheet and gets listed in the
 * preview's variant box, while `?mode=` for it is dropped here. Selecting that
 * mode is a no-op. The bound is kept anyway: a name that long is pathological,
 * and an unbounded value on a public query param is not something to trade for
 * it.
 *
 * A value outside the class is treated as NO PARAMETER AT ALL — no attribute,
 * no warning, still `200`. Never a `400`: the resource is a document, and this
 * route has never answered an input problem with an error status.
 */
const SAFE_VARIANT = /^[A-Za-z0-9_-]{1,64}$/;

/** The query param as a usable variant name, or `null` for "not asked for". */
function variantParam(raw: unknown): string | null {
  // Express hands back an array when the param repeats (`?state=a&state=b`) and
  // an object for `?state[x]=y`. Neither is a variant name.
  if (typeof raw !== 'string') return null;
  return SAFE_VARIANT.test(raw) ? raw : null;
}

/** Defensive parse of the embedded `states` JSON column — a document, never a 500. */
function parseStateNames(raw: unknown): string[] {
  let value = raw;
  if (typeof value === 'string') {
    try {
      value = JSON.parse(value);
    } catch {
      return [];
    }
  }
  if (!Array.isArray(value)) return [];
  return value
    .map((item) =>
      item && typeof item === 'object' && typeof (item as { name?: unknown }).name === 'string'
        ? (item as { name: string }).name
        : null,
    )
    .filter((name): name is string => name !== null);
}

/**
 * `config.language` holds a DISPLAY NAME (`'Polski'`), not a BCP-47 tag, and
 * the host exposes no mapping — so the table lives here, next to its only
 * consumer. Anything unknown falls back to `en`; a wrong `lang` is a hint to
 * the screen reader and the hyphenator, never a rendering failure.
 */
const LANGUAGE_TAGS: Record<string, string> = {
  English: 'en',
  Polski: 'pl',
  Deutsch: 'de',
  'Español': 'es',
  'Français': 'fr',
  'Português': 'pt',
  Italiano: 'it',
  Nederlands: 'nl',
  '日本語': 'ja',
  '中文': 'zh',
};

/**
 * Read the project's authoring language off disk.
 *
 * `MountContext` carries no config — `ctx.cwd` is the only handle — so the file
 * is read here. Best-effort by design: a missing or malformed config must yield
 * a document, not a 500.
 */
function projectLang(cwd: string): string {
  try {
    const raw = readFileSync(join(cwd, '.claude4spec', 'config.json'), 'utf8');
    const language = (JSON.parse(raw) as { language?: unknown }).language;
    // `Object.hasOwn`, not a truthiness test on the index: `language` is an
    // unvalidated config value, so `"toString"` would otherwise pass the check
    // and return a FUNCTION typed as `string` — which throws downstream and
    // turns this best-effort read into the 500 it exists to avoid.
    if (typeof language === 'string' && Object.hasOwn(LANGUAGE_TAGS, language)) {
      return LANGUAGE_TAGS[language];
    }
  } catch {
    // no config, unreadable, or not JSON — `en` is a fine answer to all three.
  }
  return 'en';
}

export function uiViewMockupRouter(ctx: MockupMountContext): Router {
  const router = Router();

  router.get('/:slug/mockup', (req, res, next) => {
    try {
      const view = ctx.reader.getEntity(UI_VIEW_TYPE, req.params.slug);
      if (!view) {
        return res
          .status(404)
          .json({ error: { code: 'NOT_FOUND', message: `ui-view '${req.params.slug}' not found` } });
      }

      // A `RawEntity`'s `data` is the projection ROW, so it is keyed by COLUMN.
      const data = view.data as Record<string, unknown>;
      const dsSlug = typeof data.design_system_slug === 'string' ? data.design_system_slug : null;
      const mockupHtml = typeof data.mockup_html === 'string' ? data.mockup_html : null;
      const title = typeof data.title === 'string' ? data.title : view.slug;

      // The two variant axes. Whitelisted HERE, before either value can reach
      // the composer — see `SAFE_VARIANT`.
      const state = variantParam(req.query.state);
      const mode = variantParam(req.query.mode);

      let stylesheet = '';
      let missingDesignSystemSlug: string | null = null;
      let modeNames: string[] = [];

      // In-process, through the host — never an internal HTTP call and never a
      // direct import of the service class. Both types ship in one envelope,
      // which is the only reason this reach across types is legal at all.
      const service = ctx.host.getEntityService(DESIGN_SYSTEM_TYPE) as
        | { stylesheetFor(groups: unknown[], modes: unknown[]): string }
        | null;

      if (dsSlug) {
        // Through the M39 core, not the raw reader: `groups`/`modes` are
        // declared collections, so they live in child tables and the
        // projection row does not carry them.
        // Guarded, because `getEntities` calls `requireActiveType` and THROWS
        // `INVALID_TYPE` when `design-system` is absent from `config.entities`.
        // `dependsOn` is a soft ordering hint, not referential integrity, so a
        // project that whitelists `ui-view` alone is reachable — and there the
        // documented degradation (a document without tokens) must still win over
        // a JSON error. An unreadable design system is a MISSING one.
        let ds: { groups?: unknown; modes?: unknown } | null | undefined;
        try {
          const found = ctx.discovery().getEntities({ type: DESIGN_SYSTEM_TYPE, slugs: [dsSlug] });
          ds = found.results.find((r) => r.slug === dsSlug)?.entity as
            | { groups?: unknown; modes?: unknown }
            | null
            | undefined;
        } catch {
          ds = null;
        }
        if (!ds) {
          // `onMissing: 'warn'` — a dangling ref degrades, it does not fail.
          missingDesignSystemSlug = dsSlug;
        } else {
          const modes = parseModes(ds.modes);
          modeNames = modes.map((m) => m.name);
          stylesheet = service ? service.stylesheetFor(parseGroups(ds.groups), modes) : '';
        }
      }

      if (!stylesheet) {
        // No design system, a dangling one, or a service that is somehow not
        // registered: the reset alone is still a valid, renderable sheet.
        stylesheet = service ? service.stylesheetFor([], []) : '';
      }

      res.setHeader('Content-Type', 'text/html; charset=utf-8');
      res.setHeader('X-Content-Type-Options', 'nosniff');
      res.setHeader('Content-Security-Policy', SANDBOX_CSP);
      // Forced by the resource's STRUCTURE: the document composes TWO entities,
      // so editing the design system does not change the view's URL, and the
      // browser's heuristic caching would happily show a stale mockup. After an
      // edit, a plain reload of the same address must show the new content —
      // without a hard refresh.
      res.setHeader('Cache-Control', 'no-store');

      // Character-safe but undeclared: the attribute still goes out, verbatim,
      // and so does a comment saying nothing styles it. A view with no design
      // system has no mode vocabulary at all, so every `?mode=` there is
      // unknown by definition — `modeNames` is empty and the check needs no
      // special case for it.
      const declaredStates = parseStateNames(data.states);
      const unknownState = state && !declaredStates.includes(state) ? state : null;
      const unknownMode = mode && !modeNames.includes(mode) ? mode : null;

      // Raw document bytes — NOT a `{ data }` envelope. A resource consumed as
      // a document or as an iframe `src` carries its own Content-Type, because
      // wrapping it in JSON would make it unrenderable.
      res.send(
        renderMockupDocument({
          title,
          mockupHtml,
          stylesheet,
          lang: projectLang(ctx.cwd),
          missingDesignSystemSlug,
          state,
          mode,
          unknownState,
          unknownMode,
        }),
      );
    } catch (err) {
      next(err);
    }
  });

  return router;
}
