/**
 * The published tarball must carry the builtin envelope.
 *
 * This is a test rather than a note because the failure is silent and total: if
 * the envelope's bundles are missing from the package, `discoverBuiltinEnvelopes()`
 * returns `[]` — no error, no warning — and every installed host quietly has no
 * `endpoint` and no `dto` type at all. Nothing in the app would report it; the
 * two sidebar tabs would simply be absent.
 *
 * The envelope is emitted into the host's own `dist/plugins/<name>/`, not into a
 * `dist/` beside its source, precisely so that this holds for free: `files`
 * already names `dist`, and so does every container image's `COPY`. An earlier
 * revision built it beside the source and added `.npmignore` gymnastics to drag
 * it into the tarball — which shipped correctly on npm and then failed in the
 * first env-runner smoke test, whose Dockerfile copies `/app/dist` and nothing
 * else. One artifact location, one rule.
 *
 * This test therefore guards the emit location as much as the packaging.
 */

import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { describe, expect, it } from 'vitest';

const REPO_ROOT = path.join(import.meta.dirname, '../../..');

/** Every envelope in `plugins/` must reach the tarball on the same terms. */
const ENVELOPES = [
  'c4s-plugin-api-contracts',
  'c4s-plugin-spreadsheets',
  'c4s-plugin-database-tables',
  'c4s-plugin-frontend-mockups',
  'c4s-plugin-mcp-tools',
];

describe('npm package contents', () => {
  it('ships every builtin envelope’s built bundles', () => {
    // `--dry-run --json` lists the file set without writing a tarball. Slow
    // (npm walks the tree), hence the raised timeout rather than a smaller check.
    const raw = execFileSync('npm', ['pack', '--dry-run', '--json'], {
      cwd: REPO_ROOT,
      encoding: 'utf-8',
      stdio: ['ignore', 'pipe', 'ignore'],
    });
    const [tarball] = JSON.parse(raw) as Array<{ files: Array<{ path: string }> }>;
    const files = (tarball?.files ?? []).map((f) => f.path);

    for (const name of ENVELOPES) {
      // The backend entry the loader imports, and the frontend bundle the asset
      // route serves. Either one missing breaks a different half of the feature.
      expect(files, name).toContain(`dist/plugins/${name}/index.js`);
      expect(files, name).toContain(`dist/plugins/${name}/frontend.js`);
      // `discoverBuiltinEnvelopes` reads `exports`/`main` from here to find the
      // entry. It is generated by the envelope build, not copied: the source
      // manifest's paths carry a `dist/` segment the output directory already
      // consumes, so a copy would point one level too deep.
      expect(files, name).toContain(`dist/plugins/${name}/package.json`);

      // Code-split chunks are siblings of the entries and are fetched by relative
      // specifier, so a `files` rule narrow enough to catch only the two named
      // bundles would produce a bundle that loads and then 404s mid-import.
      expect(
        files.filter((f) => new RegExp(`^dist/plugins/${name}/.*\\.js$`).test(f)).length,
        `${name} code-split chunks`,
      ).toBeGreaterThan(2);
    }
  }, 120_000);
});

/**
 * The other half of "an envelope ships correctly": its *styles*.
 *
 * Envelope bundles emit no CSS of their own — they render into the host's
 * document and rely entirely on the single stylesheet Tailwind generates from
 * `tailwind.config.js`. Tailwind only emits a utility it has literally seen in
 * a scanned file, so a class used *only* inside `plugins/` is generated only if
 * `plugins/` is in `content`.
 *
 * This was invisible for three releases because every envelope happened to use
 * utilities `src/client` also used. Extracting `ui-view` + `design-system` in
 * 0.2.18 was the first move to take arbitrary values (`text-[14.5px]`,
 * `text-[9px]`, `pr-4`) out of `src/client` entirely — the classes stayed in the
 * markup, the rules vanished from the stylesheet, and nothing failed: the cards
 * just silently rendered at the inherited font size.
 */
describe('tailwind content globs', () => {
  it('scans envelope sources, not just src/client', async () => {
    const config = (await import(path.join(REPO_ROOT, 'tailwind.config.js'))).default as {
      content: string[];
    };
    expect(config.content).toContain('./plugins/*/src/**/*.{ts,tsx}');
  });
});
