import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import { createTestApp, type TestApp } from '../../helpers/test-app.js';
import { fixtureModule } from '../../helpers/fixture-module.js';

/**
 * The keyed write door as a PLUGIN receives it — `ctx.crud`, not the host
 * internals behind it.
 *
 * `generic-crud.keyed.test.ts` pins the host half against an in-memory database.
 * What only this level can show is the facade WRAPPER: the async binding and the
 * `entity:changed` broadcast built in `buildProjectContext` and mirrored here.
 * The broadcast is the one effect no other assertion can reach — it leaves no
 * trace in the database or the entity file — and the facade's own comment
 * records that it was missing once already, so every open client kept rendering
 * a stale entity until someone reloaded by hand.
 *
 * The type is a registered fixture, not a shipped one: no entity type in this
 * repo declares a keyed collection yet (the spreadsheet plugin is the intended
 * first consumer). It goes through the real registration path, so its projection
 * tables are generated by the same machinery a real type's are.
 */
const grid = fixtureModule('grid', {
  withEntityService: true,
  data: {
    schema: {
      title: { kind: 'string', required: true, maxLength: 200, default: 'Untitled' },
      nRows: { kind: 'number', column: 'n_rows', default: 0 },
      nCols: { kind: 'number', column: 'n_cols', default: 0 },
      cells: {
        kind: 'collection',
        collection: 'keyed',
        keyFields: ['r', 'c'],
        axes: [
          { key: 'r', extent: 'nRows' },
          { key: 'c', extent: 'nCols' },
        ],
        item: {
          kind: 'object',
          fields: {
            r: { kind: 'number', required: true },
            c: { kind: 'number', required: true },
            value: { kind: 'string' },
          },
        },
      },
      updatedAt: { kind: 'string', column: 'updated_at', systemManaged: true, computedDefault: 'now' },
    },
  },
});

describe('ctx.crud — the keyed collection write door a plugin is handed', () => {
  let t: TestApp;

  beforeEach(async () => {
    t = await createTestApp({ extraModules: [grid] });
    await t.crud.create('grid', { title: 'Sheet', nRows: 3, nCols: 3 }, 'user');
    t.broadcasts.length = 0;
  });
  afterEach(() => t.cleanup());

  const cells = () => t.db.prepare('SELECT r, c, value FROM grid_cells ORDER BY r, c').all();
  const entityFile = () =>
    JSON.parse(fs.readFileSync(path.join(t.cwd, '.claude4spec/entities/grid/sheet.json'), 'utf8'));

  it('writes a cell, persists the entity file and tells every open client', async () => {
    const result = await t.crud.writeCollectionWindow('grid', 'sheet', 'cells', [{ r: 2, c: 3, value: 'hi' }], 'user');

    expect(result).toEqual({ slug: 'sheet' });
    expect(cells()).toEqual([{ r: 2, c: 3, value: 'hi' }]);
    expect(entityFile().cells).toEqual([{ r: 2, c: 3, value: 'hi' }]);
    expect(t.broadcasts).toEqual([{ kind: 'entity:changed', entityType: 'grid', slug: 'sheet' }]);
  });

  it('merges a second write instead of replacing the grid — the reason this verb exists', async () => {
    await t.crud.writeCollectionWindow('grid', 'sheet', 'cells', [{ r: 1, c: 1, value: 'a' }], 'user');
    await t.crud.writeCollectionWindow('grid', 'sheet', 'cells', [{ r: 2, c: 2, value: 'b' }], 'user');

    expect(cells()).toEqual([
      { r: 1, c: 1, value: 'a' },
      { r: 2, c: 2, value: 'b' },
    ]);
    // Whereas `update` reconciles the same field replace-all:
    await t.crud.update('grid', 'sheet', { cells: [{ r: 3, c: 3, value: 'c' }] }, 'user');
    expect(cells()).toEqual([{ r: 3, c: 3, value: 'c' }]);
  });

  it('records ONE version per call and stamps the parent, through the facade', async () => {
    await t.crud.writeCollectionWindow(
      'grid',
      'sheet',
      'cells',
      [
        { r: 1, c: 1, value: 'a' },
        { r: 1, c: 2, value: 'b' },
        { r: 1, c: 3, value: 'c' },
      ],
      'user',
    );

    // One for the create in `beforeEach`, one for this write — not one per cell.
    expect(t.versionService.listVersions('grid', 'sheet')).toHaveLength(2);
  });

  it('mutates an axis and broadcasts that too', async () => {
    await t.crud.writeCollectionWindow(
      'grid',
      'sheet',
      'cells',
      [
        { r: 1, c: 1, value: 'a' },
        { r: 3, c: 1, value: 'c' },
      ],
      'user',
    );
    t.broadcasts.length = 0;

    const result = await t.crud.mutateCollectionAxis('grid', 'sheet', 'cells', 'r', 'insert', 2, 'user');

    expect(result).toEqual({ slug: 'sheet', extent: 4 });
    expect(cells()).toEqual([
      { r: 1, c: 1, value: 'a' },
      { r: 4, c: 1, value: 'c' },
    ]);
    expect(t.broadcasts).toEqual([{ kind: 'entity:changed', entityType: 'grid', slug: 'sheet' }]);
  });

  it('a rejected write leaves no trace — no rows, no file rewrite, no broadcast', async () => {
    await expect(
      t.crud.writeCollectionWindow('grid', 'sheet', 'cells', [{ r: 9, c: 9, value: 'past the end' }], 'user'),
    ).rejects.toThrow(/past the declared extent/);

    expect(cells()).toEqual([]);
    expect(entityFile().cells ?? []).toEqual([]);
    expect(t.broadcasts).toEqual([]);
  });
});
