/**
 * Host API 2.0.0, item 31 — `/api/{type}s`, generated by the host.
 *
 * One router built per active type from its `data.schema`, mounted under that
 * type's own `pathPrefix`. It replaces the six near-identical `routes.ts` files
 * — list / create / get / patch / delete, differing only in a table name, a
 * response key and which service they called.
 *
 * THE ENVELOPE IS L4'S, NOT MCP'S. `{ data, total }` for a list, `{ data }` for
 * one entity — the REST response format, confirmed against the specification
 * rather than inferred from the routers this replaces (which answered
 * `{ acs: [...] }`, `{ dtos: [...] }`, … — a per-type key that was never a
 * written contract). `{ items, total, hasMore }` is the MCP transport's
 * envelope and deliberately stays there. A `clarification` patch is filed: no
 * `endpoint` entity pins the REST list response, so the choice rests on L4's
 * response-format section rather than on a declared DTO.
 *
 * THE LIST VIEW IS `element_list_item`. Same rule the M39 core applies to
 * `list_entities` ("the item shape per type is the L9 list view"), so one
 * entity does not read differently depending on which transport asked. A single
 * entity comes back as `single_element` — `detail` resolves references the
 * detail panel fetches separately, and paying for that on every read would make
 * `GET /:slug` the most expensive route in the app.
 *
 * STAGING — read this before concluding the six built-ins moved. This router is
 * mounted AFTER each type's own `backend.routes` router, so wherever a domain
 * router still serves a CRUD verb it keeps serving it. Today that is all six
 * built-in types, which therefore behave exactly as before; the types this
 * router actually serves are the ones with no `routes` slot at all — which is
 * every declaratively-authored plugin, and what item 63's plug-and-play test
 * asserts. Tier K deletes the six routers, and they land here with nothing else
 * to change. Same staging as tier A's `slugPattern`.
 */

import { Router } from 'express';
import { z } from 'zod';
import { DomainError } from '../../services/tags.js';
import { errorHandler } from '../../routes/errors.js';
import { buildCreateShape, buildUpdateShape } from './crud-schema-gen.js';
import { genericCreate, genericDelete, genericUpdate, propagateRename, type GenericCrudDeps } from './generic-crud.js';
import type { DiscoveryCore } from '../../discovery/types.js';
import type { WsEmitter } from '../../ws/project-emitter.js';
import type { BackendModule } from './types.js';

export interface GeneratedCrudDeps extends GenericCrudDeps {
  discovery: DiscoveryCore;
  ws: WsEmitter;
}

/** `?tags=a,b` → `['a','b']`; absent or empty → undefined (no tag filter). */
function tagList(raw: unknown): string[] | undefined {
  if (typeof raw !== 'string') return undefined;
  const tags = raw.split(',').filter(Boolean);
  return tags.length ? tags : undefined;
}

function positiveInt(raw: unknown): number | undefined {
  if (typeof raw !== 'string' || !raw) return undefined;
  const n = Number(raw);
  return Number.isInteger(n) && n >= 0 ? n : undefined;
}

/**
 * The entity as a REST response: the L9 view, plus the audit stamp.
 *
 * `createdAt`/`updatedAt` are `systemManaged`, so `hydrate` lifts them out of
 * `data` into `RawEntity.system` and no view emits them — deliberately, since
 * they are not view CONTENT. Every client list row and detail header renders
 * them, though, so the transport re-attaches what the host owns. Doing it here
 * rather than in the views keeps one rule for all five views and all six types.
 */
function withSystem(deps: GeneratedCrudDeps, type: string, slug: string, view: unknown): unknown {
  const system = deps.reader.getEntity(type, slug)?.system;
  return system && view && typeof view === 'object' ? { ...(view as object), ...system } : view;
}

function readOne(deps: GeneratedCrudDeps, type: string, slug: string): unknown {
  const [result] = deps.discovery.getEntities({ type, slugs: [slug], view: 'single_element' }).results;
  if (!result || result.entity == null) throw new DomainError('NOT_FOUND', `${type} '${slug}' not found`);
  return withSystem(deps, type, slug, result.entity);
}

export function generatedCrudRouter(deps: GeneratedCrudDeps, module: BackendModule): Router {
  const router = Router();
  const type = module.type;
  const createSchema = z.object(buildCreateShape(module.data!));
  const updateSchema = z.object(buildUpdateShape(module.data!));

  const broadcast = (slug: string): void => {
    deps.ws.broadcast({ kind: 'entity:changed', entityType: type, slug });
  };

  /**
   * A zod rejection is a 400, not a 500.
   *
   * `errorHandler` maps `DomainError('VALIDATION')`; a bare `ZodError` reaching
   * it falls through as INTERNAL, which is how a mistyped payload would have
   * read as a server fault.
   */
  const parse = <T>(schema: z.ZodType<T>, body: unknown): T => {
    const parsed = schema.safeParse(body);
    if (!parsed.success) throw new DomainError('VALIDATION', parsed.error.message);
    return parsed.data;
  };

  router.get('/', (req, res, next) => {
    try {
      const q = req.query;
      const search = typeof q.search === 'string' ? q.search : '';
      const limit = positiveInt(q.limit);
      const offset = positiveInt(q.offset);

      /**
       * Search and tag-filter are DIFFERENT core operations, not two filters of
       * one query: `search_entities` ranks, `list_entities` enumerates in the
       * reader's order. The retired per-type SQL ANDed them into one `WHERE`,
       * which silently dropped the ranking whenever both were present.
       */
      if (search) {
        const hits = deps.discovery.searchEntities({
          type,
          query: search,
          view: 'element_list_item',
          ...(limit !== undefined ? { limit } : {}),
          ...(offset !== undefined ? { offset } : {}),
        });
        if (hits.mode !== 'hits') throw new DomainError('INTERNAL', 'search returned a count');
        res.json({
          data: hits.items.map((h) => withSystem(deps, type, h.slug, h.data)),
          total: hits.total,
        });
        return;
      }

      const page = deps.discovery.listEntities({
        type,
        view: 'element_list_item',
        ...(tagList(q.tags) ? { tags: tagList(q.tags)! } : {}),
        ...(q.tagFilter === 'and' || q.tagFilter === 'or' ? { filter: q.tagFilter } : {}),
        ...(limit !== undefined ? { limit } : {}),
        ...(offset !== undefined ? { offset } : {}),
      });
      if (page.mode !== 'items') throw new DomainError('INTERNAL', 'list returned a count');
      res.json({
        data: page.items.map((i) => withSystem(deps, type, i.slug, i.data)),
        total: page.total,
      });
    } catch (err) {
      next(err);
    }
  });

  router.post('/', (req, res, next) => {
    try {
      const input = parse(createSchema, req.body);
      const { slug } = genericCreate(deps, type, input, 'user');
      broadcast(slug);
      res.status(201).json({ data: readOne(deps, type, slug) });
    } catch (err) {
      next(err);
    }
  });

  router.get('/:slug', (req, res, next) => {
    try {
      res.json({ data: readOne(deps, type, req.params.slug) });
    } catch (err) {
      next(err);
    }
  });

  router.patch('/:slug', async (req, res, next) => {
    try {
      const body = (req.body ?? {}) as Record<string, unknown>;
      // `newSlug` is a SIBLING of the payload, not a field of it — the same
      // split `update_entities` makes, so a rename means the same thing on both
      // transports and no type has to declare a `newSlug` field to be renamable.
      const input = parse(updateSchema, { ...body, newSlug: undefined, slug: undefined });
      const newSlug = typeof body.newSlug === 'string' ? body.newSlug : undefined;
      const previous = req.params.slug;
      const { slug } = genericUpdate(
        deps,
        type,
        previous,
        { ...input, ...(newSlug !== undefined ? { newSlug } : {}) },
        'user',
      );
      await propagateRename(deps, type, previous, slug);
      broadcast(slug);
      res.json({ data: readOne(deps, type, slug) });
    } catch (err) {
      next(err);
    }
  });

  router.delete('/:slug', async (req, res, next) => {
    try {
      const slug = req.params.slug;
      /**
       * Reported, not repaired. A markdown reference to a deleted entity stays
       * in the page — the client shows it as broken and the author decides.
       * Counted per page, which is the shape every retired router returned.
       */
      const hits = await deps.references.findReferences(type as never, slug);
      const counts = new Map<string, number>();
      for (const h of hits) counts.set(h.pagePath, (counts.get(h.pagePath) ?? 0) + 1);
      const result = genericDelete(deps, type, slug, 'user');
      if (!result.deleted) throw new DomainError('NOT_FOUND', `${type} '${slug}' not found`);
      broadcast(slug);
      res.json({
        deleted: true,
        brokenReferences: Array.from(counts, ([pagePath, count]) => ({ pagePath, count })),
      });
    } catch (err) {
      next(err);
    }
  });

  router.use(errorHandler);
  return router;
}
