/**
 * Host API 2.0.0, item 31 — `/api/{type}s`, generated by the host.
 *
 * One router built per active type from its `data.schema`, mounted under that
 * type's own `pathPrefix`. It replaces the six near-identical `routes.ts` files
 * — list / create / get / patch / delete, differing only in a table name, a
 * response key and which service they called.
 *
 * THE ENVELOPE IS L4'S, NOT MCP'S. `{ data, total }` for a list, `{ data }` for
 * one entity — the REST response format, confirmed against the specification
 * rather than inferred from the routers this replaces (which answered
 * `{ acs: [...] }`, `{ dtos: [...] }`, … — a per-type key that was never a
 * written contract). `{ items, total, hasMore }` is the MCP transport's
 * envelope and deliberately stays there. A `clarification` patch is filed: no
 * `endpoint` entity pins the REST list response, so the choice rests on L4's
 * response-format section rather than on a declared DTO.
 *
 * THE LIST VIEW IS `element_list_item`. Same rule the M39 core applies to
 * `list_entities` ("the item shape per type is the L9 list view"), so one
 * entity does not read differently depending on which transport asked.
 *
 * A single entity comes back as `single_element` by DEFAULT, and `?view=detail`
 * asks for the expensive one. Paying for the joins on every read would make
 * `GET /:slug` the most expensive route in the app; never offering them at all —
 * which is what this router did until the parameter was wired — makes the detail
 * views unreachable, and they are where `dto.endpoints` and the `_references`
 * back-pointers live.
 *
 * TIER K un-staged this. The router used to be mounted AFTER each type's own
 * `backend.routes`, so wherever a domain router still served a CRUD verb it kept
 * serving it. Those six routers are gone; every built-in type is served from
 * here, from its declaration, exactly as a declaratively-authored plugin is
 * (item 63's plug-and-play test asserts the same surface for a type the host has
 * never heard of).
 */

import { Router } from 'express';
import { z } from 'zod';
import { DomainError } from '../../services/tags.js';
import { getEntitiesAll } from '../../discovery/index.js';
import { errorHandler } from '../../routes/errors.js';
import { buildCreateShape, buildUpdateShape } from './crud-schema-gen.js';
import { genericCreate, genericDelete, genericUpdate, propagateRename, type GenericCrudDeps } from './generic-crud.js';
import { isEmbedded, type FieldNode } from '../../../shared/plugin-host/data-schema.js';
import type { DiscoveryCore } from '../../discovery/types.js';
import type { WsEmitter } from '../../ws/project-emitter.js';
import type { BackendModule } from './types.js';

export interface GeneratedCrudDeps extends GenericCrudDeps {
  discovery: DiscoveryCore;
  ws: WsEmitter;
}

/** `?tags=a,b` → `['a','b']`; absent or empty → undefined (no tag filter). */
function tagList(raw: unknown): string[] | undefined {
  if (typeof raw !== 'string') return undefined;
  const tags = raw.split(',').filter(Boolean);
  return tags.length ? tags : undefined;
}

function positiveInt(raw: unknown): number | undefined {
  if (typeof raw !== 'string' || !raw) return undefined;
  const n = Number(raw);
  return Number.isInteger(n) && n >= 0 ? n : undefined;
}

/** Query keys this router owns; everything else is a candidate field filter. */
// `view` left this set in 0.2.22 along with the parameter; `sort`/`dir` joined
// it, or a type declaring a field called `sort` would have its ordering read as
// a field filter.
const RESERVED_QUERY_KEYS = new Set(['search', 'tags', 'tagFilter', 'limit', 'offset', 'sort', 'dir']);

/** `'3'` → `3`, `'true'` → `true` — a query string carries no types of its own. */
function coerceFilterValue(node: FieldNode, raw: string): string | number | boolean | undefined {
  if (node.type === 'number') {
    const n = Number(raw);
    return Number.isFinite(n) ? n : undefined;
  }
  if (node.type === 'boolean') {
    if (raw === 'true') return true;
    if (raw === 'false') return false;
    return undefined;
  }
  return raw;
}

/**
 * `?field=value` → `filters`, derived from the declaration (item 56–61's
 * replacement for the hand-parsed `?status=` / `?kind=` of the retired routers).
 *
 * Every declared EMBEDDED scalar is filterable, comma-separated values meaning
 * `IN` — the same rule `RawEntityReader.slugsMatching` applies to the MCP
 * transport, so one type does not answer two different questions depending on
 * who asked. Unknown keys are ignored rather than rejected, which is the
 * contract `list_entities` has always advertised.
 *
 * `?field=all` — the "lift the default" sentinel — is NOT handled here. It is
 * `slugsMatching`'s, so `?status=all` and `filters: { status: 'all' }` mean the
 * same thing; implementing it in this router made it mean "everything" over
 * HTTP and "nothing" over MCP, which is the worse of the two ways to disagree.
 */
function queryFilters(module: BackendModule, q: Record<string, unknown>): Record<string, unknown> {
  const schema = module.data!.schema;
  const filters: Record<string, unknown> = {};
  for (const [key, raw] of Object.entries(q)) {
    if (RESERVED_QUERY_KEYS.has(key) || typeof raw !== 'string' || raw === '') continue;
    // Own properties only — `?valueOf=1` must not resolve to `Object.prototype`.
    if (!Object.hasOwn(schema, key)) continue;
    const node = schema[key]!;
    if (!isEmbedded(node) || node.type === 'json') continue;
    const values = raw
      .split(',')
      .filter(Boolean)
      .map((v) => coerceFilterValue(node, v))
      .filter((v) => v !== undefined);
    if (values.length) filters[key] = values;
  }
  return filters;
}

/**
 * The entity as a REST response: the L9 view, plus the audit stamp.
 *
 * `createdAt`/`updatedAt` are `systemManaged`, so `hydrate` lifts them out of
 * `data` into `RawEntity.system` and no view emits them — deliberately, since
 * they are not view CONTENT. Every client list row and detail header renders
 * them, though, so the transport re-attaches what the host owns. Doing it here
 * rather than in the views keeps one rule for all five views and all six types.
 */
function withSystem(deps: GeneratedCrudDeps, type: string, slug: string, view: unknown): unknown {
  return attachStamp(view, deps.reader.getEntity(type, slug)?.system);
}

/** The list form: one batched stamp read for the page, not one read per row. */
function withSystemAll(
  deps: GeneratedCrudDeps,
  type: string,
  items: ReadonlyArray<{ slug: string; data: unknown }>,
): unknown[] {
  const stamps = deps.reader.systemStamps(type, items.map((i) => i.slug));
  return items.map((i) => attachStamp(i.data, stamps.get(i.slug)));
}

function attachStamp(view: unknown, system: { createdAt: string; updatedAt: string } | undefined): unknown {
  return system && view && typeof view === 'object' ? { ...(view as object), ...system } : view;
}

/**
 * One entity, at the full projection.
 *
 * 0.2.22 retired the `?view=` parameter this function used to take. The reason
 * it existed — `detail` carries the joins (`dto.endpoints`, the `_references`
 * back-pointers) that a detail page needs and a list row does not — is now
 * served by `get_entities` serializing the widest view and projecting, so a GET
 * gets the joins without anybody naming a view.
 */
function readOne(deps: GeneratedCrudDeps, type: string, slug: string): unknown {
  const [result] = deps.discovery.getEntities({ type, slugs: [slug] }).results;
  if (!result || result.entity == null) throw new DomainError('NOT_FOUND', `${type} '${slug}' not found`);
  return withSystem(deps, type, slug, result.entity);
}

/**
 * Turn discovery rows into the records this route has always returned.
 *
 * 0.2.22 froze the `list_entities` row to `{ slug, title }`, which is right for
 * discovery and not enough for a list PAGE — the UI renders a description, a
 * method, a parameter count. So the two questions are asked separately: the core
 * decides WHICH entities and in what order, and one batched `get_entities` says
 * what they contain. One extra call per page, not per row.
 *
 * No `select`: the default projection is already "everything but the
 * content-bearing fields", which is exactly what a list wants — and it is the
 * same rule the agent-facing channel gets, so the UI has no privileged width.
 *
 * `getEntitiesAll`, NOT `getEntities`: this route's default page is 200 while
 * the core operation refuses more than 50 slugs in one call. That cap is the
 * agent's contract and is right for it; a page the server itself just decided
 * the size of is not overreaching, so it batches instead of being refused.
 */
function hydrateRows(deps: GeneratedCrudDeps, type: string, rows: Array<{ slug: string }>): unknown[] {
  if (!rows.length) return [];
  const { results } = getEntitiesAll(deps.discovery, { type, slugs: rows.map((r) => r.slug) });
  return withSystemAll(
    deps,
    type,
    results.filter((r) => r.entity != null).map((r) => ({ slug: r.slug, data: r.entity })),
  );
}

export function generatedCrudRouter(deps: GeneratedCrudDeps, module: BackendModule): Router {
  const router = Router();
  const type = module.type;
  const createSchema = z.object(buildCreateShape(module.data!, module.slugPattern));
  const updateSchema = z.object(buildUpdateShape(module.data!, module.slugPattern));

  const broadcast = (slug: string): void => {
    deps.ws.broadcast({ kind: 'entity:changed', entityType: type, slug });
  };

  /**
   * A zod rejection is a 400, not a 500.
   *
   * `errorHandler` maps `DomainError('VALIDATION')`; a bare `ZodError` reaching
   * it falls through as INTERNAL, which is how a mistyped payload would have
   * read as a server fault.
   */
  const parse = <T>(schema: z.ZodType<T>, body: unknown): T => {
    const parsed = schema.safeParse(body);
    if (!parsed.success) throw new DomainError('VALIDATION', parsed.error.message);
    return parsed.data;
  };

  router.get('/', (req, res, next) => {
    try {
      const q = req.query;
      const search = typeof q.search === 'string' ? q.search : '';
      /**
       * The page size a LIST PAGE gets when it asks for no page at all.
       *
       * The M39 core defaults to 50, which is right for an agent reading over
       * stdio and wrong here: every retired service defaulted to 200, and not
       * one client list page reads `total`/`hasMore` or renders a load-more
       * control, so the core's default silently hid the 51st entity of every
       * type — including from the active-AC count that gates Analyze
       * consistency. Stated here rather than changed in the core, because the
       * core's default is correct for the transport it was chosen for.
       */
      const limit = positiveInt(q.limit) ?? 200;
      const offset = positiveInt(q.offset);
      const filters = queryFilters(module, q as Record<string, unknown>);
      const tags = tagList(q.tags);
      const tagFilter: 'and' | 'or' | undefined =
        q.tagFilter === 'and' || q.tagFilter === 'or' ? q.tagFilter : undefined;

      /**
       * Search and list are DIFFERENT core operations — one ranks, one
       * enumerates in the reader's order — but every narrowing the caller
       * asked for applies to both.
       *
       * The retired per-type SQL ANDed the tag sub-select and the LIKE into one
       * WHERE, which dropped the ranking whenever both were present; keeping
       * the operations apart fixes that. What it must not do is drop the
       * narrowing itself: the list pages send `tags`, `search` and the field
       * dropdowns in ONE request, so a search path that ignored `tags` made a
       * visibly-selected tag chip stop applying the moment you typed.
       */
      const narrowing = {
        filters,
        applyDefaultPredicate: true,
        ...(tags ? { tags } : {}),
        ...(tagFilter ? { tagFilter } : {}),
      };

      if (search) {
        const hits = deps.discovery.searchEntities({
          type,
          query: search,
          limit,
          ...narrowing,
          ...(offset !== undefined ? { offset } : {}),
        });
        if (hits.mode !== 'hits') throw new DomainError('INTERNAL', 'search returned a count');
        res.json({ data: hydrateRows(deps, type, hits.items), total: hits.total });
        return;
      }

      const page = deps.discovery.listEntities({
        type,
        limit,
        ...narrowing,
        ...(offset !== undefined ? { offset } : {}),
      });
      if (page.mode !== 'items') throw new DomainError('INTERNAL', 'list returned a count');
      res.json({ data: hydrateRows(deps, type, page.items), total: page.total });
    } catch (err) {
      next(err);
    }
  });

  router.post('/', (req, res, next) => {
    try {
      const input = parse(createSchema, req.body);
      /**
       * `warnings` rides ALONGSIDE `data`, and only when there are any.
       *
       * A dangling soft ref (`onMissing: 'warn'`) is the case this exists for:
       * the write succeeded and the caller must be told what is now broken.
       * Dropping it here made the whole warning path invisible on the two doors
       * a user or an agent can actually reach.
       */
      const { slug, warnings } = genericCreate(deps, type, input, 'user');
      broadcast(slug);
      const body = { data: readOne(deps, type, slug) };
      res.status(201).json(warnings?.length ? { ...body, warnings } : body);
    } catch (err) {
      next(err);
    }
  });

  router.get('/:slug', (req, res, next) => {
    try {
      // 0.2.22 — `?view=` is gone from this route with the rest of the axis. A
      // detail page gets the full projection, and a caller wanting less says so
      // with `select` on `GET /api/entities/:type/get`.
      res.json({ data: readOne(deps, type, req.params.slug) });
    } catch (err) {
      next(err);
    }
  });

  router.patch('/:slug', async (req, res, next) => {
    try {
      const body = (req.body ?? {}) as Record<string, unknown>;
      // `newSlug` is a SIBLING of the payload, not a field of it — the same
      // split `update_entities` makes, so a rename means the same thing on both
      // transports and no type has to declare a `newSlug` field to be renamable.
      const input = parse(updateSchema, { ...body, newSlug: undefined, slug: undefined });
      const newSlug = typeof body.newSlug === 'string' ? body.newSlug : undefined;
      const previous = req.params.slug;
      const { slug, warnings } = genericUpdate(
        deps,
        type,
        previous,
        { ...input, ...(newSlug !== undefined ? { newSlug } : {}) },
        'user',
      );
      await propagateRename(deps, type, previous, slug);
      broadcast(slug);
      const out = { data: readOne(deps, type, slug) };
      res.json(warnings?.length ? { ...out, warnings } : out);
    } catch (err) {
      next(err);
    }
  });

  router.delete('/:slug', async (req, res, next) => {
    try {
      const slug = req.params.slug;
      /**
       * Reported, not repaired. A markdown reference to a deleted entity stays
       * in the page — the client shows it as broken and the author decides.
       * Counted per page, which is the shape every retired router returned.
       */
      const hits = await deps.references.findReferences(type as never, slug);
      const counts = new Map<string, number>();
      for (const h of hits) counts.set(h.pagePath, (counts.get(h.pagePath) ?? 0) + 1);
      const result = genericDelete(deps, type, slug, 'user');
      if (!result.deleted) throw new DomainError('NOT_FOUND', `${type} '${slug}' not found`);
      broadcast(slug);
      res.json({
        deleted: true,
        brokenReferences: Array.from(counts, ([pagePath, count]) => ({ pagePath, count })),
      });
    } catch (err) {
      next(err);
    }
  });

  router.use(errorHandler);
  return router;
}
